### ISSUE TITLE
Has this repo been deprecated?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-colors#7]
This repo says it _will_ be deprecated. Has it been deprecated? Can we update the copy to the present tense?

**Comment by Scotchester** [comment]
We have been leaving it up in case any projects still had cf-colors in their dependencies. I'm not sure if they are, or what the easiest way to find that out would be...

**Comment by anselmbradford** [comment]
Leaving it up is fine, but we can say it has been deprecated, right?

**Comment by Scotchester** [comment]
Yeah, for sure.
